---
- name: Install PostgreSQL packages
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: present
    update_cache: true

- name: Ensure PostgreSQL service is enabled
  ansible.builtin.service:
    name: postgresql
    enabled: true
